/**
 * Backend-driven authentication types
 * All roles and permissions are determined by the backend
 */

// Role types - Backend is single source of truth
export type UserRole = 'OWNER' | 'EMPLOYEE'

/**
 * User as returned from backend after JWT verification
 * Backend validates token and returns verified user data
 */
export interface User {
    id: string
    email: string
    name: string
    avatar?: string
    role: UserRole
    companyId: string  // Every user belongs to exactly one company
    companyName: string
    inviteStatus?: 'pending' | 'accepted'  // For employees waiting for team invite
    permissions: string[]  // Computed by backend based on role
    createdAt: string
}

/**
 * Company created during admin registration
 * Only exists once per admin user
 */
export interface Company {
    id: string
    name: string
    ownerId: string
    ownerEmail: string
    createdAt: string
}

/**
 * Team invite for adding employees to company
 * Generated by OWNER, used by employees to join
 */
export interface TeamInvite {
    id: string
    companyId: string
    email: string
    status: 'pending' | 'accepted'
    createdAt: string
    acceptedAt?: string
}

/**
 * JWT Payload structure after verification
 */
export interface JWTPayload {
    sub: string  // user ID
    email: string
    companyId: string
    role: UserRole
    iat: number
    exp: number
}
